# Generated by Django 5.2.6 on 2025-09-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('familia', models.CharField(max_length=155)),
                ('genero', models.CharField(max_length=155)),
            ],
        ),
    ]
