# Generated by Django 5.2.6 on 2025-09-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=155)),
                ('fat', models.CharField(max_length=155)),
                ('sugar', models.CharField(max_length=155)),
                ('carbohydrates', models.CharField(max_length=155)),
                ('protein', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
                ('family', models.CharField(max_length=155)),
                ('genus', models.CharField(max_length=155)),
                ('nutritions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.nutricao')),
            ],
        ),
    ]
