# Generated by Django 5.2.6 on 2025-09-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='calorias',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
