# Generated by Django 5.2.6 on 2025-09-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
